### ISSUE TITLE
Does not run on Windows 7 SP1 x64.

### ISSUE THREAD

**Issue by EDSln** [Eclipse-Community/StickShift#2]
### Problem Description

After startup the following error is displayed. Windowsdesktop runtime 6.0.30 is installed. Tried to install 6.0.31 same error.

### Activity Log, Crash Log or any other details

```text
---------------------------
Unhandled Exception
---------------------------
An Unknown Error has occurred. 

 Exception:Autofac.Core.DependencyResolutionException: An exception was thrown while activating HandBrakeWPF.Services.UserSettingService.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(HandBrakeWPF.Services.Logging.Interfaces.ILog)' on type 'UserSettingService'.
 ---> System.DllNotFoundException: Unable to load DLL 'hb' or one of its dependencies: The specified procedure was not found. (0x8007007F)
   at HandBrake.Interop.Interop.HandBrakeVersionHelper.IsNightly()
   at HandBrakeWPF.Services.UserSettingService..ctor(ILog logService)
   at lambda_method35(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass12_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ScopeSelectionMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at HandBrakeWPF.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
```

### What Operating System are you running?

Windows 7 x64 SP1 with all updates including ESU.

### What version of HandBrake are you running?

StickShift-1.7.4-x86_64-Win_GUI.exe

**Comment by the-r3dacted** [comment]
Yeah, the latest release is kinda fucked up. This is what I get for not testing before I make it a release. Even with no real code changes two new functions were added to hb.dll that make it incompatible with 7. I have no idea why or how to fix it. You can grab hb.dll from one of the earlier GitHub Actions things and it will work though.

**Comment by EDSln** [comment]
The dll from №11 works.

**Comment by KennReloaded** [comment]
The files are expired. Can you please publish the last working version?

**Comment by EDSln** [comment]
> The files are expired. Can you please publish the last working version?

Good thing I saved the file.
https://mega.nz/file/DvRwHbKJ#QQ2m6jq58lrSUs_WVPmDvLKyIfs_K8D8lpVuHTqOCFc

**Comment by KennReloaded** [comment]
thanks but it doesnt seem to have the needed dll. im still getting the error message.

**Comment by KennReloaded** [comment]
> Good thing I saved the file. https://mega.nz/file/DvRwHbKJ#QQ2m6jq58lrSUs_WVPmDvLKyIfs_K8D8lpVuHTqOCFc

im sorry i might did not make it clear, i need the working hb.dll.

**Comment by EDSln** [comment]
This version is working, do you have windowsdesktop runtime 6.0.29-6.0.35 installed? 
Here is the dll from this version https://mega.nz/file/brYSWRbQ#2nVvhuyS85oaekVaRxZ9E-8ACELv-rPUkmEKQIGwGBE

**Comment by KennReloaded** [comment]
https://mega.nz/file/brYSWRbQ#2nVvhuyS85oaekVaRxZ9E-8ACELv-rPUkmEKQIGwGBE
awesome, this is exactly it! works now, thank you so much!
